spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true #log SQL queries
    properties:
      hibernate:
        format_sql: true #better readability
logging:
  level:
    org.springframework: DEBUG
jwt:
  rsa-private-key: classpath:certs/privateKey.pem
  rsa-public-key: classpath:certs/publicKey.pem

#  security:
#    user:
#      name: "kaarthik"
#      password: "password"
#logging:
#  level:
#    org.springframework: DEBUG
#    org.springframework.web: DEBUG
#    # com.assign1.demo: DEBUG
